// <auto-generated />
namespace PlayNow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _3migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201702202124161_3migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
